baseURL = "https://chammock.dev"
title = "Curtis Hammock | Developer"

theme = "hugo-coder"

languagecode="en"
defaultcontentlanguage="en"

paginate =20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

# Custom CSS
custom_css = []

# Custom JS
custom_js = []


[params]
    author = "Curtis Hammock"
    info = "Full Stack Security Cloud Developer"
    description = "Curtis Hammock's developer website"
    keywords = "blog,developer,cloud"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/images/favicon-32x32.png"
    favicon_16 = "/images/favicon-16x16.png"

    colorscheme = "dark"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/chammock/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/curtishammock/"


# Menu links
[[menu.main]]
    name = "About"
    weight = 10
    url = "/about/"
[[menu.main]]
    name = "Certs"
    weight = 20
    url = "/certs/"
[[menu.main]]
    name = "Blog"
    weight = 30
    url = "/posts/"
[[menu.main]]
    name = "Contact"
    weight = 40
    url = "/contact/"